# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yinhao/project/glgo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yinhao/project/glgo/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yinhao/project/glgo/build/CMakeFiles /home/yinhao/project/glgo/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yinhao/project/glgo/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glgo

# Build rule for target.
glgo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glgo
.PHONY : glgo

# fast build rule for target.
glgo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/build
.PHONY : glgo/fast

Math.o: Math.cpp.o
.PHONY : Math.o

# target to build an object file
Math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Math.cpp.o
.PHONY : Math.cpp.o

Math.i: Math.cpp.i
.PHONY : Math.i

# target to preprocess a source file
Math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Math.cpp.i
.PHONY : Math.cpp.i

Math.s: Math.cpp.s
.PHONY : Math.s

# target to generate assembly for a file
Math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Math.cpp.s
.PHONY : Math.cpp.s

Render.o: Render.cpp.o
.PHONY : Render.o

# target to build an object file
Render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Render.cpp.o
.PHONY : Render.cpp.o

Render.i: Render.cpp.i
.PHONY : Render.i

# target to preprocess a source file
Render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Render.cpp.i
.PHONY : Render.cpp.i

Render.s: Render.cpp.s
.PHONY : Render.s

# target to generate assembly for a file
Render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Render.cpp.s
.PHONY : Render.cpp.s

Screen.o: Screen.cpp.o
.PHONY : Screen.o

# target to build an object file
Screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Screen.cpp.o
.PHONY : Screen.cpp.o

Screen.i: Screen.cpp.i
.PHONY : Screen.i

# target to preprocess a source file
Screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Screen.cpp.i
.PHONY : Screen.cpp.i

Screen.s: Screen.cpp.s
.PHONY : Screen.s

# target to generate assembly for a file
Screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/Screen.cpp.s
.PHONY : Screen.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glgo.dir/build.make CMakeFiles/glgo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glgo"
	@echo "... Math.o"
	@echo "... Math.i"
	@echo "... Math.s"
	@echo "... Render.o"
	@echo "... Render.i"
	@echo "... Render.s"
	@echo "... Screen.o"
	@echo "... Screen.i"
	@echo "... Screen.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

